### ISSUE TITLE
BUG: wrong result about { 

### ISSUE THREAD

**Issue by lihz1990** [peakwinter/python-nginx#12]
```python
import nginx

TESTBLOCK="""
upstream test0 {
    ip_hash;
    server 127.0.0.1:8080;
    keepalive 16; 
}
upstream test1{
    server 127.0.0.2:8080;
    keepalive 16; 
}
upstream test2
{
    server 127.0.0.3:8080;
    keepalive 16; 
}

server {
    listen       80;
    server_name  example.com;

    location = / 
    {       
        root html;
    }   
}
"""


u1 = nginx.loads(TESTBLOCK)
print u1.children[0].value
print u1.children[1].value
print u1.children[2].value

nginx.dumpf(u1, '/tmp/example.conf')
```

For upstream test0 , ip_hash  lost.
For upstream test1 and test2 ,  upstream name changed, result is test .
For location section, raise error: 
```
Traceback (most recent call last):
  File "example.py", line 32, in <module>
    u1 = nginx.loads(TESTBLOCK)
  File "/usr/local/lib/python2.7/dist-packages/nginx.py", line 454, in loads
    if isinstance(lopen[0], Server):
IndexError: list index out of range
```

**Comment by peakwinter** [comment]
Should be fixed in 1.3!
