### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JoyChou93** [peakwinter/python-nginx#16]
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

```
>>> import nginx
>>> nginx.loadf('/tmp/nginx.conf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nginx.py", line 492, in loadf
    return load(f)
  File "/Library/Python/2.7/site-packages/nginx.py", line 482, in load
    return loads(fobj.read())
  File "/Library/Python/2.7/site-packages/nginx.py", line 454, in loads
    if isinstance(lopen[0], Server):
IndexError: list index out of range
```

**Comment by peakwinter** [comment]
Hi there,

Could you please provide a sample of the NGINX configuration you were trying to load here?

Thank you.

**Comment by JoyChou93** [comment]
nginx.conf

```

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
	    root   /usr/local/var/www/;

        location / {
            index  index.html index.php;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }


    	if (!-e $request_filename) {
            rewrite ^(.*)$ /index.php$1 last;
        }

        location ~ [^/]\.php(/|$) {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_split_path_info ^(.+?.php)(/.*)$; 
            fastcgi_index index.php;
	       include        fastcgi_params;
	       fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
	   }
        
    }

    server {
        listen       81;
        server_name  test.baidu.com;
    }


    include servers/*;
}

```

**Comment by peakwinter** [comment]
This should be fixed in 1.3. Thanks!

**Comment by JoyChou93** [comment]
After updating 1.3 ver, still return null list.

```
import nginx


c = nginx.loadf('/usr/local/etc/nginx/nginx.conf')
print(c.filter('Server'))
```

**Comment by peakwinter** [comment]
For now, filters will only go one level deep, so you would need to do:

```python
c.filter('Http')[0].filter('Server')
```
